version: '3.1'

services:
  jrtb-db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: 'dev_jrtb_db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'pass'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'